package com.si.backend.service;

import com.si.backend.common.Constants;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.Locale;

/**
 * Applies deterministic backend speed-up to mono 16-bit PCM generated by TTS.
 */
@Slf4j
@Service
public class TtsPcmSpeedService {

    private static final int PCM_BYTES_PER_SAMPLE = 2;
    private static final double SPEED_EPSILON = 0.0001;
    private static final short MIN_SAMPLE = Short.MIN_VALUE;
    private static final short MAX_SAMPLE = Short.MAX_VALUE;

    public double resolveBackendSpeed(String targetLang) {
        String normalized = normalizeLang(targetLang);
        if (normalized.startsWith("id")) {
            return Constants.TTS_BACKEND_SPEED_ID;
        }
        if (normalized.startsWith("zh")) {
            return Constants.TTS_BACKEND_SPEED_ZH;
        }
        return Constants.TTS_BACKEND_SPEED_DEFAULT;
    }

    public PcmSpeedProcessor processor(String targetLang) {
        return new PcmSpeedProcessor(resolveBackendSpeed(targetLang));
    }

    private static String normalizeLang(String targetLang) {
        return targetLang == null ? "" : targetLang.trim().toLowerCase(Locale.ROOT);
    }

    public static final class PcmSpeedProcessor {
        private final double speed;
        private double nextSourceOffset;

        private PcmSpeedProcessor(double speed) {
            this.speed = speed <= 0 ? Constants.TTS_BACKEND_SPEED_DEFAULT : speed;
        }

        public double speed() {
            return speed;
        }

        public byte[] process(byte[] pcm) {
            if (pcm == null || pcm.length == 0 || isNeutralSpeed()) {
                return pcm;
            }
            if (pcm.length < PCM_BYTES_PER_SAMPLE || pcm.length % PCM_BYTES_PER_SAMPLE != 0) {
                log.warn("[TtsPcmSpeedService] skip backend PCM speed-up, reason=invalidPcmBytes, bytes={}, speed={}",
                        pcm.length, speed);
                return pcm;
            }

            int inputSamples = pcm.length / PCM_BYTES_PER_SAMPLE;
            int outputSamples = countOutputSamples(inputSamples);
            if (outputSamples <= 0) {
                return new byte[0];
            }
            byte[] output = new byte[outputSamples * PCM_BYTES_PER_SAMPLE];
            double sourcePosition = nextSourceOffset;
            for (int i = 0; i < outputSamples; i++) {
                int sample = interpolateSample(pcm, inputSamples, sourcePosition);
                writeSample(output, i, sample);
                sourcePosition += speed;
            }
            nextSourceOffset = sourcePosition - inputSamples;
            return output;
        }

        private boolean isNeutralSpeed() {
            return Math.abs(speed - Constants.TTS_BACKEND_SPEED_DEFAULT) < SPEED_EPSILON;
        }

        private int countOutputSamples(int inputSamples) {
            int count = 0;
            double sourcePosition = nextSourceOffset;
            while (sourcePosition < inputSamples) {
                count++;
                sourcePosition += speed;
            }
            return count;
        }

        private static int interpolateSample(byte[] pcm, int inputSamples, double sourcePosition) {
            int baseIndex = Math.max(0, Math.min((int) Math.floor(sourcePosition), inputSamples - 1));
            int nextIndex = Math.min(baseIndex + 1, inputSamples - 1);
            double fraction = sourcePosition - baseIndex;
            short left = readSample(pcm, baseIndex);
            short right = readSample(pcm, nextIndex);
            return clampToShort((int) Math.round(left + (right - left) * fraction));
        }

        private static short readSample(byte[] pcm, int sampleIndex) {
            int offset = sampleIndex * PCM_BYTES_PER_SAMPLE;
            return (short) ((pcm[offset] & 0xff) | (pcm[offset + 1] << 8));
        }

        private static void writeSample(byte[] output, int sampleIndex, int sample) {
            int offset = sampleIndex * PCM_BYTES_PER_SAMPLE;
            output[offset] = (byte) (sample & 0xff);
            output[offset + 1] = (byte) ((sample >>> 8) & 0xff);
        }

        private static int clampToShort(int sample) {
            return Math.max(MIN_SAMPLE, Math.min(MAX_SAMPLE, sample));
        }
    }
}
