ALTER TABLE si_user ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE si_user ADD COLUMN token_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE si_user ADD COLUMN last_login_time DATETIME NULL;
ALTER TABLE si_user ADD COLUMN password_changed_at DATETIME NULL;
